# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 615e0ceb967a9034ddbec3a56a7bee8b69bee5e1933e65b9077b1c7c860e64384acbf6b14c68ff8982754520a71a8644066442d463541a1ba1180fa1d5fe1196

test:
  secret_key_base: 4fd5d94df9010190710f96b01efc64d9cea20b6be0e833ebd80d9360e3a81ec43ead3153760d8be3cb566f0c167ed926ea0f4d7b6d43624be00d5400a51c70c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
